[package]
name = "hmm-utils"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
glob = "0.3.1"
serde = { workspace = true, features = ["derive"] }
